### ISSUE TITLE
Python 2.7 EOL

### ISSUE THREAD

**Issue by nrosier** [Jerrythafast/se-logger#3] opened 2020-03-09 12:26 UTC
Any plans to port to 3?

**Comment by Jerrythafast** [comment] 2020-03-09 16:51
That shouldn't be too difficult to achieve.

**Comment by expaso** [comment] 2020-05-02 21:21
That should give you a headstart. I also needed it :)

**Comment by Jerrythafast** [comment] 2020-05-10 14:49
Thanks again for the PR!

**Comment by Jerrythafast** [comment] 2020-05-13 20:52
The python 3 code is not working yet... reopening to fix and test further.

**Comment by RobBie1221** [comment] 2020-05-14 13:52
On line 208 of liveupdate.py there is a syntax error ('byterray' should be 'bytearray').

Fixing this still did not work for me. Line 511:

`db.execute("UPDATE live_update SET last_0503 = %s", (msg,))`

Did not work for me either. I get an error wrong length of 0503 entry. It seems the msg is now bytearray, but this is wrongly handled here. I changed it to:

`db.execute("UPDATE live_update SET last_0503 = %s", (bytes(msg),))`

After changing that, I got it it working. It succesfully rebuilt my database with ~1.5y of data. I do have to check whether entries are correct, but it looks good.

I did not review other code to see it is correctly adjusted for the bytearray, but it seems so as it runs.

EDIT:
Maybe cheered too soon. I have one pcap file where the 0.0.10 version correctly detects end of file, but the 0.0.15 version after above patches give an error:

Traceback (most recent call last):
  File "liveupdate_new.py", line 508, in <module>
    for hdr, msg in parser.get_messages(byteiterator):
  File "liveupdate_new.py", line 158, in get_messages
    for byte in byteiterator:
  File "liveupdate_new.py", line 304, in get_data_from_pcap
    f.read(packet_offset)
ValueError: read length must be positive or -1

Here I'm triggering the following code:

`if ethertype != b"\x08\x00":
          # Not IPv4 packet, skip this.
          # TODO: IPv6 support.
          f.read(packet_offset)
          continue`

The value for packet_offset is -14
Here python 2.7 accepts f.read(-14) and closes nicely.
Python 3 does not accept negative values in f.read except for -1

In python 2.7, if size is negative it returns the remainder of the file, basically skipping the rest of the file. In python 3, it does the same but is more strict (only -1 is allowed).
My file was pretty much finished after it hits this, I have a bunch of zeros left over, nothing relevant I guess. Question would be whether this is expected behavior, to flush the file once it detects one non-IPv4 packet?

On a side note, strange thing is that this "non IPv4" packet is only seen once after approximately 1y3m in use...

**Comment by Jerrythafast** [comment] 2020-05-15 18:59
> Here I'm triggering the following code:
> 
> `if ethertype != b"\x08\x00": # Not IPv4 packet, skip this. # TODO: IPv6 support. f.read(packet_offset) continue`
> 
> The value for packet_offset is -14
> Here python 2.7 accepts f.read(-14) and closes nicely.
> Python 3 does not accept negative values in f.read except for -1
> 
> In python 2.7, if size is negative it returns the remainder of the file, basically skipping the rest of the file. In python 3, it does the same but is more strict (only -1 is allowed).
> My file was pretty much finished after it hits this, I have a bunch of zeros left over, nothing relevant I guess. Question would be whether this is expected behavior, to flush the file once it detects one non-IPv4 packet?
> 
> On a side note, strange thing is that this "non IPv4" packet is only seen once after approximately 1y3m in use...

Since you are saying it has only a bunch of zeros left over: could it be that this particular file is damaged/truncated? A `packet_offset` of -14 implies that the record header in the pcap file already had 0 as the length of saved data (read at line 292). That means the file should continue with the next packet header, which cannot be all zeroes. So if the remainder of the file contains zeroes it is damaged. In that case, the script goes on to read the `ethertype` as zero, and then run into the crash you encountered.

I think it makes sense to put an `if not packet_offset: continue` on line 293 anyway, that should solve this too.

**Comment by RobBie1221** [comment] 2020-05-15 19:24
My guess was as well it's damaged. I have a cronjob to restart the service daily to make a new file as suggested. This particular file is 'solaredge-20190327233004.pcap', so it ended at the expected time. I do not miss data from that day, so any corruption has no effect on the data.

My best guess, could it be the cronjob runs at the same moment tcpdump is writing to the file and this corrupts the file at the end? It's an off-chance this happens, because at night the traffic is low, perhaps that's why it only occurred once so far in ~1.5y.

It's anyway not a big issue for me because as said, I don't seem to miss data. I temporarily fixed it with a f.read(-1), but I think your proposal is a nicer solution.

With the changes above (line 208, 511 and your proposal on 293), it's working perfectly fine for me in python3.

**Comment by Jerrythafast** [comment] 2020-05-15 19:39
All right, I made these changes now. If you don't run into any more issues I hope this solves everything and we can close the issue again :) I'll leave it open just a little while longer, if nothing else pops up I'll release the latest code as 0.0.16. Thanks for being the guinea pig 😜

**Comment by nrosier** [comment] 2020-06-06 20:36
Not sure if it's related to the upgrade of Python. I re-installed my RPI and moved to the latest version of se-logger with Python3. When running as a service I get following error:
```
Reading from -
Traceback (most recent call last):
  File "/opt/se-logger/liveupdate.py", line 512, in <module>
    for hdr, msg in parser.get_messages(byteiterator):
  File "/opt/se-logger/liveupdate.py", line 158, in get_messages
    for byte in byteiterator:
  File "/opt/se-logger/liveupdate.py", line 278, in get_data_from_pcap
    byteorder = {b"\xD4\xC3\xB2\xA1": "<", b"\xA1\xB2\xC3\xD4": ">"}[f.read(pcaphdrlen)[:4]]
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 0: invalid continuation byte
```
When running liveupdate.py and specifying the files it works. Looks like reading from stdin is not working with the current locale but I cannot find how to fix this. Any ideas?

**Comment by Jerrythafast** [comment] 2020-06-06 20:47
I think I know what's going on. It is not reading binary data from stdin, but unicode text instead. In `liveupdate.py`, could you replace `f = sys.stdin` with `f = sys.stdin.buffer`, restart the service and report whether that helped?

**Comment by nrosier** [comment] 2020-06-06 21:18
That's what I was just playing with. Both sys.stdin.buffer and sys.stdin.buffer.raw seem to work fine. Not sure which one is best (my scripting days date back to perl...) but sys.stdin.buffer seems to be te equivalent of binmode in perl so probably what is needed.

The service is starting without issue but as it's night I cannot see if all is working as expected. But doing cat <pcap> | liveupdate.py - does not  give the error and parses the file correctly so I think that fixes is.

**Comment by Jerrythafast** [comment] 2020-06-06 21:35
The main difference seems to be the behaviour when the end of the stream has been reached (i.e., tcpdump stopped). I think using `sys.stdin.buffer` is the more appropriate choice here.

**Comment by Jerrythafast** [comment] 2020-06-20 08:28
After two weeks of silence, I've wrapped the updates up into an official release. Hope it all works fine now!

**Closed as completed by Jerrythafast** 2020-06-20 08:28 UTC
